export const vehicles = [
  {
    id: 1,
    marca: "Toyota",
    modelo: "Corolla",
    placa: "EJE-111",
    color: "Rojo",
    tipo: "MinuBus",
    capacidad: 5,
    status: "Activo",
    chasis: "JTDBE32K123456789",
    año: 2020,
    serie: "SER-001",
    ficha: "FICHA-1001",
    pasoRapido: false,
    codigoPasoRapido: null,
  },
  {
    id: 2,
    marca: "Ford",
    modelo: "Focus",
    placa: "EXA-999",
    color: "Azul",
    tipo: "Bus",
    capacidad: 5,
    status: "Activo",
    chasis: "1FAHP3FN8AW123456",
    año: 2019,
    serie: "SER-002",
    ficha: "FICHA-1002",
    pasoRapido: true,
    codigoPasoRapido: 42423,
  },
  {
    id: 3,
    marca: "Chevrolet",
    modelo: "Tahoe",
    placa: "ABC-456",
    color: "Negro",
    tipo: "SUV",
    capacidad: 7,
    status: "Inactivo",
    chasis: "1GNSKCKJ2HR123456",
    año: 2021,
    serie: "SER-003",
    ficha: "FICHA-1003",
    pasoRapido: false,
    codigoPasoRapido: null,
  },
    {
      id: 4,
      marca: "Toyota",
      modelo: "Corolla",
      placa: "EJE-112",
      color: "Rojo",
      tipo: "Carro",
      capacidad: 5,
      status: "Activo",
      chasis: "1GNSKCKJ2HR123404",
      año: 2021,
      serie: "SER-004",
      ficha: "FICHA-1004",
      pasoRapido: true,
      codigoPasoRapido: 42023,
    },
    {
      id: 5,
      marca: "Ford",
      modelo: "Focus",
      placa: "EXA-899",
      color: "Azul",
      tipo: "MiniBus",
      capacidad: 5,
      status: "Activo",
      chasis: "2FAHP3FN8AW123405",
      año: 2022,
      serie: "SER-005",
      ficha: "FICHA-1005",
      pasoRapido: true,
      codigoPasoRapido: 42453,
    },
    {
      id: 6,
      marca: "Chevrolet",
      modelo: "Tahoe",
      placa: "ABC-457",
      color: "Negro",
      tipo: "SUV",
      capacidad: 7,
      status: "Inactivo",
      chasis: "3FAHP3FN8AW123406",
      año: 2023,
      serie: "SER-006",
      ficha: "FICHA-1006",
      pasoRapido: false,
      codigoPasoRapido: null,
    },
    {
      id: 7,
      marca: "Toyota",
      modelo: "Corolla",
      placa: "EJE-123",
      color: "Rojo",
      tipo: "Carro",
      capacidad: 5,
      status: "Activo",
      chasis: "2FAHP3FN8AW123407",
      año: 2019,
      serie: "SER-007",
      ficha: "FICHA-1007",
      pasoRapido: true,
      codigoPasoRapido: 42423,
    },
    {
      id: 8,
      marca: "Ford",
      modelo: "Focus",
      placa: "EXA-789",
      color: "Azul",
      tipo: "MiniBus",
      capacidad: 5,
      status: "Activo",
      chasis: "2FAHP3FN8AW123408",
      año: 2020,
      serie: "SER-008",
      ficha: "FICHA-1008",
      pasoRapido: true,
      codigoPasoRapido: 42423,
    },
    {
      id: 9,
      marca: "Chevrolet",
      modelo: "Tahoe",
      placa: "ABC-478",
      color: "Negro",
      tipo: "SUV",
      capacidad: 7,
      status: "Inactivo",
      chasis: "2FAHP3FN8AW123409",
      año: 2021,
      serie: "SER-009",
      ficha: "FICHA-1009",
      pasoRapido: false,
      codigoPasoRapido: null,
    },
    {
      id: 10,
      marca: "Chevrolet",
      modelo: "Tahoe",
      placa: "ABC-789",
      color: "Negro",
      tipo: "SUV",
      capacidad: 7,
      status: "Inactivo",
      chasis: "2FAHP3FN8AW123410",
      año: 2022,
      serie: "SER-010",
      ficha: "FICHA-1010",
      pasoRapido: false,
      codigoPasoRapido: null,
    },
  ];